### ISSUE TITLE
hash update meshcommander

### ISSUE THREAD

**Issue by CharlPels** [mkopnsrc/chocolatey-packages#8]
Can you update the hash for meshcommander?
There is a new version 1.1.0

new hash: E284FA77A20B57D62A998078142EECD9F2C985BEFE32B948BD69E2D355ECF9E1

**Comment by CharlPels** [comment]
new hash

**Comment by mkopnsrc** [comment]
@CharlPels  the original site still have the version v0.9.6. I don't see any new version of 1.1.0.

**Comment by mkopnsrc** [comment]
No plan to update checksum until new version comes on https://www.meshcommander.com/
